package com.radiantsage.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-05-05T23:31:18.433+05:30
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "ProductService", 
                  wsdlLocation = "file:./src/main/webapp/WEB-INF/wsdl/product.wsdl",
                  targetNamespace = "http://service.radiantsage.com") 
public class ProductService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.radiantsage.com", "ProductService");
    public final static QName ProductServiceSoapBinding = new QName("http://service.radiantsage.com", "ProductServiceSoapBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:./src/main/webapp/WEB-INF/wsdl/product.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./src/main/webapp/WEB-INF/wsdl/product.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProductService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSoapBinding")
    public ProductService getProductServiceSoapBinding() {
        return super.getPort(ProductServiceSoapBinding, ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSoapBinding")
    public ProductService getProductServiceSoapBinding(WebServiceFeature... features) {
        return super.getPort(ProductServiceSoapBinding, ProductService.class, features);
    }

}
