
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.radiantsage.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-05-05T23:31:18.156+05:30
 * Generated source version: 3.2.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ProductService",
                      portName = "ProductServiceSoapBinding",
                      targetNamespace = "http://service.radiantsage.com",
                      wsdlLocation = "file:./src/main/webapp/WEB-INF/wsdl/product.wsdl",
                      endpointInterface = "com.radiantsage.service.ProductService")
                      
public class ProductServiceSoapBindingImpl implements ProductService {

    private static final Logger LOG = Logger.getLogger(ProductServiceSoapBindingImpl.class.getName());

    /* (non-Javadoc)
     * @see com.radiantsage.service.ProductService#registerProduct(com.radiantsage.model.Product product)*
     */
    public com.radiantsage.model.Product registerProduct(com.radiantsage.model.Product product) { 
        LOG.info("Executing operation registerProduct");
        System.out.println(product);
        try {
            com.radiantsage.model.Product _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
