
package com.radiantsage.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-05-06T00:16:58.688+05:30
 * Generated source version: 3.2.0
 * 
 */
 
public class ProductServiceServer{

    protected ProductServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new com.radiantsage.service.ProductServiceImpl();
        String address = "http://localhost:9090/ProductServicePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ProductServiceServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 