
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.radiantsage.service;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2019-05-06T00:16:58.603+05:30
 * Generated source version: 3.2.0
 * 
 */
@WebService(endpointInterface = "com.radiantsage.service.ProductService", serviceName = "ProductServiceService")                      
public class ProductServiceImpl implements ProductService {

    public com.radiantsage.model.Product registerProduct(com.radiantsage.model.Product arg0) {  
        System.out.println(arg0);
try {
            com.radiantsage.model.Product _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }

    }

}
